Fix grammar in level 3 description
mozilla/inclusion pull request #308
Opened 2023-08-17 22:10 UTC by babolivier

2023-08-29 09:07 UTC, couci approved these changes
thanks for your contribution

2023-09-17 20:29 UTC, josehz5578 approved these changes

2023-09-18 09:31 UTC, merged

2023-09-18 22:29 UTC, janiaz708 commented
hi

2024-01-10 19:58 UTC, Md0135 commented on code-of-conduct-enforcement/consequence-ladder.md
Türkiye

2024-01-11 19:59 UTC, Md0135 reviewed
Türkiye

2024-01-11 20:01 UTC, Md0135 reviewed
Türkiye

2024-01-15 04:09 UTC, janiaz708 commented
hi

2024-03-19 12:01 UTC, PAOLASSS999 reviewed
code-of-conduct-enforcement/consequence-ladder.md

2024-03-24 15:31 UTC, Setarland commented
abb1a6846e71f371d044b09ccd50e9dd5914c856

2024-03-24 15:32 UTC, Setarland approved these changes

2024-06-06 20:03 UTC, Mikypearl commented
Hello

2024-09-14 11:03 UTC, Ebaoone approved these changes

2024-09-14 11:05 UTC, Ebaoone approved these changes

2024-09-14 11:06 UTC, Ebaoone commented on code-of-conduct-enforcement/consequence-ladder.md
f887bc3932bb5dc72ee0bd0bda3985266bdb5be4

2025-01-23 14:57 UTC, Tihana08 approved these changes

2025-02-08 14:03 UTC, Daveydave101 reviewed
T

2025-02-08 14:04 UTC, Daveydave101 approved these changes
[]()

2025-02-08 14:04 UTC, Daveydave101 requested changes
[]()

2025-02-08 14:05 UTC, Daveydave101 reviewed
[]()

2025-02-08 14:09 UTC, Daveydave101 commented on code-of-conduct-enforcement/consequence-ladder.md
2b5367b1525f67709fb3485c873847db646a3699

2025-02-08 14:09 UTC, Daveydave101 approved these changes

2025-02-08 14:10 UTC, Daveydave101 approved these changes
- [Copper Boom ]

2025-03-15 02:09 UTC, Dustin4444 approved these changes